const FETCH_USER = 'FETCH_USER'
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
const FETCH_USER_FAILED = 'FETCH_USER_FAILED'
const USER_SIGN_IN = 'USER_SIGN_IN'
const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED'
const USER_SIGN_OUT = 'USER_SIGN_OUT'
const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
const SIGN_UP_USER = 'SIGN_UP_USER'
const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS'
const SIGN_UP_USER_FAILED = 'SIGN_UP_USER_FAILED'

const FETCH_ALL_VEHICLES = 'FETCH_ALL_VEHICLES'
const FETCH_ALL_VEHICLES_SUCCESS = 'FETCH_ALL_VEHICLES_SUCCESS'
const FETCH_ALL_VEHICLES_FAILED = 'FETCH_ALL_VEHICLES_FAILED'
const DELETE_VEHICLE = 'DELETE_VEHICLE'
const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS'
const DELETE_VEHICLE_FAILED = 'DELETE_VEHICLE_FAILED'
const ADD_VEHICLE = 'ADD_VEHICLE'
const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS'
const ADD_VEHICLE_FAILED = 'ADD_VEHICLE_FAILED'

export {
    FETCH_USER,
    FETCH_USER_SUCCESS,
    FETCH_USER_FAILED,
    USER_SIGN_IN,
    USER_SIGN_IN_SUCCESS,
    USER_SIGN_IN_FAILED,
    USER_SIGN_OUT,
    CLEAR_AUTH_ERROR,
    SIGN_UP_USER,
    SIGN_UP_USER_SUCCESS,
    SIGN_UP_USER_FAILED,
    FETCH_ALL_VEHICLES,
    FETCH_ALL_VEHICLES_SUCCESS,
    FETCH_ALL_VEHICLES_FAILED,
    DELETE_VEHICLE,
    DELETE_VEHICLE_SUCCESS,
    DELETE_VEHICLE_FAILED,
    ADD_VEHICLE,
    ADD_VEHICLE_SUCCESS,
    ADD_VEHICLE_FAILED,
}
